# Scaling In Machine Learning Practice

#### Scaling: 
         Scale down continuous values either dependent or independent to range -1 to 1 or 0 to 1 so that fluctuating ranges 
         i.e columns having with different scaled values high values and low values make model difficult and time consume 
         to calculate distance for data point from other all data points hence scale down values to lower equal ranges to 
         speed up model prediction in KNN.
#### 4 Types of scaling:
         1. StandardScaling - used lot - work on z score - z=data-mean(data)/std(data).
         2. MinMaxScaling - sensitive to outliers in data.
         3. RobustScaling - suitable for outliers in data.
         4. Normalization - Rarely used.

### Data Getting

In [1]:
# Importing Packages
import pandas as pd

In [2]:
# Preparing Data
data=pd.DataFrame({'salary':[12000,20000,10000,50000],'age':[28,30,50,32]})
data

salary  age
0   12000   28
1   20000   30
2   10000   50
3   50000   32

### Scaling Packages Importing 

In [11]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, normalize 

### 1. Standard Scalling

In [8]:
# modeling
std=StandardScaler()
data['stdfied']=std.fit_transform(data['salary'].values.reshape(-1,1))
data

salary  age   stdfied
0   12000   28 -0.686161
1   20000   30 -0.187135
2   10000   50 -0.810918
3   50000   32  1.684214

In [10]:
# transforming back to original values - use the model used fot fitting
std.inverse_transform(data['stdfied'].values.reshape(-1,1))

array([[12000.],
       [20000.],
       [10000.],
       [50000.]])

### 2. MinMaxScaling

In [13]:
# modeling
mx=MinMaxScaler()
data['mxfied']=mx.fit_transform(data['salary'].values.reshape(-1,1))
data

salary  age   stdfied  mxfied
0   12000   28 -0.686161    0.05
1   20000   30 -0.187135    0.25
2   10000   50 -0.810918    0.00
3   50000   32  1.684214    1.00

In [14]:
# transforming back to original values - use the model used fot fitting
mx.inverse_transform(data['mxfied'].values.reshape(-1,1))

array([[12000.],
       [20000.],
       [10000.],
       [50000.]])

### 3. RobustScaling

In [15]:
# modeling
rbs=RobustScaler()
data['rbsfied']=rbs.fit_transform(data['salary'].values.reshape(-1,1))
data

salary  age   stdfied  mxfied  rbsfied
0   12000   28 -0.686161    0.05   -0.250
1   20000   30 -0.187135    0.25    0.250
2   10000   50 -0.810918    0.00   -0.375
3   50000   32  1.684214    1.00    2.125

In [16]:
# transforming back to original values - use the model used for fitting
rbs.inverse_transform(data['rbsfied'].values.reshape(-1,1))

array([[12000.],
       [20000.],
       [10000.],
       [50000.]])